spring:
  datasource:
    url: jdbc:mysql://gz-cdb-l3v7rxjj.sql.tencentcdb.com:58907/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: dev_wet
    password: b7l5XuU+GVh6hM6R
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 120.25.240.101 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: iamredis # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

minio:
  endpoint: http://175.178.255.153:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: mogu2018 #访问的key
  secretKey: mogu2018 #访问的秘钥

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
  enableInnerLog: false
